#!/bin/bash
current_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cronjob="*/10 * * * * /bin/bash $current_dir/start"
# Remove previous cronjob
crontab -l 2>/dev/null | grep -v "/bin/bash $current_dir/start"  | crontab -
# Create new cronjob
(crontab -l 2>/dev/null ; echo "$cronjob") | crontab -