#!/bin/bash
# Resets any configuration to default state

# stop a currently running access point routine
source stop

# delete cronjob
current_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
target="/bin/bash $current_dir/start"
crontab -l 2>/dev/null | grep -v "$target"  | crontab -

# delete configuration and data files
rm conf.yaml
rm data.db
rm main.log*