#!/bin/bash
# Starts the main routine for running the access point
# if it is not running yet
if [ $(pgrep -c "${0##*/}") -le 1 ] ; then
    current_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    cd $current_dir
    venv/bin/python3 access_point.py
fi
